### ISSUE TITLE
Does not seem to work on edge

### ISSUE THREAD

**Issue by marchellodev** [roelandmoors/authjs-adapter-sql#17]
Hey! Thanks for this package!

I am trying to run it with the latest auth.js (0.8.2). On localhost everything is ok, but in production (in a cloudflare worker), when a new user signs up, I am constantly getting the same error. Existing users can log in just fine.

I have tried both kysely and planetscale adapters

```
  "logs": [
    {
      "message": [
        "[90m[auth][debug]:[0m authorization result",
        "{
  "user": {
    "id": "111931645743874431597",
    "name": "Mark",
    "email": "marchellodev@gmail.com",
    "image": "https://lh3.googleusercontent.com/a/AAcHTtew-yni6JbFVbVLSfId-bnigqMqgDBzSbKa1IH9=s96-c"
  },
  "account": {
    "provider": "google",
    "type": "oidc",
    "providerAccountId": "...",
    "access_token": "...",
    "expires_in": 3599,
    "scope": "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email openid",
    "token_type": "bearer",
    "id_token": "...",
    "expires_at": 1686395013
  },
  "profile": {
...
  },
  "cookies": [
    {
      "name": "__Secure-next-auth.pkce.code_verifier",
      "value": "",
      "options": {
        "httpOnly": true,
        "sameSite": "lax",
        "path": "/",
        "secure": true,
        "maxAge": 0
      }
    }
  ]
}"
      ],
      "level": "log",
      "timestamp": 1686391414129
    },
    {
      "message": [
        "[90m[auth][debug]:[0m adapter_getUserByAccount",
        "{
  "args": [
    {
      "providerAccountId": "111931645743874431597",
      "provider": "google"
    }
  ]
}"
      ],
      "level": "log",
      "timestamp": 1686391414129
    },
    {
      "message": [
        "[31m[auth][error][AuthorizedCallbackError][0m: Read more at https://errors.authjs.dev#authorizedcallbackerror"
      ],
      "level": "error",
      "timestamp": 1686391414160
    },
    {
      "message": [
        "[31m[auth][cause][0m:",
        "TypeError: Cannot read properties of undefined (reading 'email')
    at signIn (worker.js:28990:20)
    at handleAuthorized (worker.js:6346:30)
    at callback (worker.js:6397:41)
    at async AuthInternal (worker.js:6953:29)
    at async Auth (worker.js:7090:28)
    at async respond (worker.js:39432:22)
    at async Object.fetch (worker.js:39715:12)"
      ],
      "level": "error",
      "timestamp": 1686391414160
    },
    {
      "message": [
        "[31m[auth][details][0m:",
        "{}"
      ],
      "level": "error",
      "timestamp": 1686391414160
    }
  ],
```

**Comment by roelandmoors** [comment]
Did you add the correct callback urls for production in the Google app?
https://authjs.dev/reference/core/errors/#authorizedcallbackerror

Not sure if this is an error in this package

**Comment by marchellodev** [comment]
yes, the callback url is correct.

It seems like a problem with auth.js 0.8.2, authjs 0.7.1 works fine

**Comment by roelandmoors** [comment]
Ah, you mean [@auth/core](https://authjs.dev/reference/core).
That is not supported yet because it is still experimental as far as I know.
I tried to support it a while back, but the testing library didn't seem ready.

Maybe I have to look into it again.

**Comment by roelandmoors** [comment]
I started a new branch for this: https://github.com/roelandmoors/authjs-adapter-sql/tree/core

What framework are you using? Do you have a simple test project maybe?

**Comment by roelandmoors** [comment]
And can you try version 1.0.0-rc1 ?

**Comment by marchellodev** [comment]
Thank you so much! I’ll be able to test it out on my project tomorrow

сб, 10 черв. 2023 р. о 16:28 Roeland ***@***.***> пише:

**Comment by marchellodev** [comment]
I've just tested it, does not work on the latest version, getting the same error.

I am using sveltekit if that helps, but I doubt it does, I think the cloudflare and a new version of @auth/core is to blame as locally everything works fine

**Comment by marchellodev** [comment]
Also the problem is reproducible only with google auth, magic links work fine

**Comment by roelandmoors** [comment]
Thanks for the feedback. I only tested on React and not on edge yet, but I hope to get this working on edge soon.
You removed 'profile' in the error output, but is that information filled and does it have an email?
Do you have an account 'google/111931645743874431597' in your database?

I leave this open for now. Hopefully we get some extra feedback or a newer version of @auth/core solves this.

Maybe I need to add a logger option to find the actual error.

**Comment by marchellodev** [comment]
no, I do not have the account in my database. The problem only appears when trying to sign up, log in works fine

**Comment by marchellodev** [comment]
I was using the kysely adapter previously, adapted from this PR

https://github.com/nextauthjs/next-auth/pull/5464

But the sign up is also broken after the update

**Comment by roelandmoors** [comment]
I guess something is broken in core then. 
Just in case, I added a new verbose option in the [configuration](https://github.com/roelandmoors/authjs-adapter-sql#configuration)

**Comment by roelandmoors** [comment]
There is also a debug function in Authjs: https://next-auth.js.org/configuration/options#debug
